version: '2.3'

services:
  benchmark:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: benchmark
    hostname: benchmark
    tty: true
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 10s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    entrypoint: ["esrally", "race", "--pipeline=benchmark-only", "--target-host=elasticsearch:9200", "--track=percolator"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:elastic", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 10
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
